[theme]
primaryColor = "#2c3e50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#2c3e50"

[server]
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
